application:
  subdomain: trilium-notes
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://trilium-notes:8080/
services:
  trilium-notes:
    # triliumnext/trilium:v0.98.1
    image: docker.1ms.run/triliumnext/trilium:v0.98.1
    environment:
      - TZ=Asia/Shanghai
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    binds:
      - /lzcapp/var/data:/home/node/trilium-data
