package: community.lazycat.app.trilium-notes
version: 0.104.1
name: Trilium Notes
description: Trilium Notes 是一款免费且开源、跨平台的阶层式笔记应用程序，专注于建立大型个人知识库。
min_os_version: 1.5.0
homepage: https://github.com/TriliumNext/Trilium
author: TriliumNext
locales:
  zh:
    name: Trilium Notes
    description: Trilium Notes 是一款免费且开源、跨平台的阶层式笔记应用程序，专注于建立大型个人知识库。
  zh_CN:
    name: Trilium Notes
    description: Trilium Notes 是一款免费且开源、跨平台的阶层式笔记应用程序，专注于建立大型个人知识库。
  en:
    name: Trilium Notes
    description: Trilium Notes is a free and open-source, cross-platform hierarchical note taking application with focus on building large personal knowledge bases.
